let shopitemsdata = [
  {
    id: "wdwd",
    name: " DELL Laptop",
    price: 40005,
    desc: "500GB hhd, 8gb RAM,TOUCH SCREEN, HAS A BACKLIGHT KEYBOARD",
    img: "images/image1.jpg",
  },
  {
    id: "wdfd",
    name: "Hp revollve 810",
    price: 60000,
    desc: "500GB hhd, 8gb RAM,TOUCH SCREEN, HAS A BACKLIGHT KEYBOARD",
    img: "images/image2.jpg",
  },
  {
    id: "wwerdwd",
    name: "LENOVO THINK PAD ",
    price: 40000,
    desc: "1TB hhd, 16gb RAM,TOUCH SCREEN, HAS A BACKLIGHT KEYBOARD",
    img: "images/image3.jpg",
  },
  {
    id: "wdyuwfgd",
    name: "LENOVO",
    price: 90000,
    desc: "500GB SSd, 16gb RAM,TOUCH SCREEN",
    img: "images/image4.jpg",
  },
  {
    id: "wdyufwfgd",
    name: "HP Laptop",
    price: 65000,
    desc: "256GB hhd, 8gb RAM,TOUCH SCREEN, HAS A BACKLIGHT KEYBOARD",
    img: "images/image4.jpg",
  },
  {
    id: "wdfdf",
    name: "Hp revollve 810",
    price: 56000,
    desc: "500GB hhd, 8gb RAM,TOUCH SCREEN, HAS A BACKLIGHT KEYBOARD",
    img: "images/image5.jpg",
  },
  {
    id: "wdfdd",
    name: "TESLA ",
    price: 16000,
    desc: "5PB hhd, 128gb RAM,TOUCH SCREEN, HAS A BACKLIGHT KEYBOARD",
    img: "images/image6.jpg",
  },
  {
    id: "wdfdj",
    name: "MOTOROLA",
    price: 35000,
    desc: "500GB hhd, 8gb RAM,TOUCH SCREEN, HAS A BACKLIGHT KEYBOARD",
    img: "images/image7.jpg",
  },
  {
    id: "wdfdl",
    name: "NOKIA",
    price: 30000,
    desc: "500GB hhd, 8gb RAM,TOUCH SCREEN, HAS A BACKLIGHT KEYBOARD",
    img: "images/image8.jpg",
  },
];